### ISSUE TITLE
Panic when deleting and recreating Snowflake Writer Tables

### ISSUE THREAD

**Issue by plmwong** [paybyphone/terraform-provider-keboola#42]
Getting a `panic` on an interface conversion when applying changes that require removing and recreating the Snowflake Writer.

Re-running the same `apply` command succeeds since at that point the `.tfstate` recognises it only needs to perform a resource creation.

```
panic: interface conversion: interface {} is *schema.Set, not []interface {}
2018-07-11T18:12:23.667-0700 [DEBUG] plugin.terraform-provider-keboola.exe:
2018-07-11T18:12:23.667-0700 [DEBUG] plugin.terraform-provider-keboola.exe: goroutine 511 [running]:
2018-07-11T18:12:23.667-0700 [DEBUG] plugin.terraform-provider-keboola.exe: github.com/plmwong/terraform-provider-keboola/plugin/providers/keboola.resourceKeboolaSnowflakeWriterTablesUpdate(0xc04226e8c0, 0xd92680, 0xc042366430, 0x24, 0x138b320)
2018-07-11T18:12:23.667-0700 [DEBUG] plugin.terraform-provider-keboola.exe:     C:/go/src/github.com/plmwong/terraform-provider-keboola/plugin/providers/keboola/resource_keboola_snowflake_writer_tables.go:178 +0x1a5d
2018-07-11T18:12:23.667-0700 [DEBUG] plugin.terraform-provider-keboola.exe: github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc04233f490, 0xc042864af0, 0xc0422b5ee0, 0xd92680, 0xc042366430, 0x1, 0xc0423a5b90, 0xc0423a5b90)
2018-07-11T18:12:23.667-0700 [DEBUG] plugin.terraform-provider-keboola.exe:     C:/go/src/github.com/hashicorp/terraform/helper/schema/resource.go:233 +0x260
2018-07-11T18:12:23.667-0700 [DEBUG] plugin.terraform-provider-keboola.exe: github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc04233fab0, 0xc042864aa0, 0xc042864af0, 0xc0422b5ee0, 0x180000, 0x0, 0xc7d000)
2018-07-11T18:12:23.667-0700 [DEBUG] plugin.terraform-provider-keboola.exe:     C:/go/src/github.com/hashicorp/terraform/helper/schema/provider.go:283 +0xab
2018-07-11T18:12:23.667-0700 [DEBUG] plugin.terraform-provider-keboola.exe: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc0424d3f60, 0xc0422b5e60, 0xc042516b30, 0x0, 0x0)
2018-07-11T18:12:23.667-0700 [DEBUG] plugin.terraform-provider-keboola.exe:     C:/go/src/github.com/hashicorp/terraform/plugin/resource_provider.go:527 +0x5e
2018-07-11T18:12:23.668-0700 [DEBUG] plugin.terraform-provider-keboola.exe: reflect.Value.call(0xc0420433e0, 0xc042156d90, 0x13, 0xdeed1b, 0x4, 0xc04245df20, 0x3, 0x3, 0x0, 0x0, ...)
2018-07-11T18:12:23.668-0700 [DEBUG] plugin.terraform-provider-keboola.exe:     C:/tools/go/src/reflect/value.go:434 +0x90c
2018-07-11T18:12:23.668-0700 [DEBUG] plugin.terraform-provider-keboola.exe: reflect.Value.Call(0xc0420433e0, 0xc042156d90, 0x13, 0xc04245df20, 0x3, 0x3, 0x0, 0x0, 0xc0424dee60)
2018-07-11T18:12:23.668-0700 [DEBUG] plugin.terraform-provider-keboola.exe:     C:/tools/go/src/reflect/value.go:302 +0xab
2018-07-11T18:12:23.668-0700 [DEBUG] plugin.terraform-provider-keboola.exe: net/rpc.(*service).call(0xc04239b8c0, 0xc042077770, 0xc0423efb70, 0xc042144400, 0xc04243a4e0, 0xc6de00, 0xc0422b5e60, 0x16, 0xc6de40, 0xc042516b30, ...)
2018-07-11T18:12:23.668-0700 [DEBUG] plugin.terraform-provider-keboola.exe:     C:/tools/go/src/net/rpc/server.go:381 +0x149
2018-07-11T18:12:23.668-0700 [DEBUG] plugin.terraform-provider-keboola.exe: created by net/rpc.(*Server).ServeCodec
2018-07-11T18:12:23.668-0700 [DEBUG] plugin.terraform-provider-keboola.exe:     C:/tools/go/src/net/rpc/server.go:475 +0x372
```

**Comment by plmwong** [comment]
Have not encountered this bug in the last few runs of Snowflake Writer Table recreation, but will be keeping it open while investigation continues.

**Comment by wtran63** [comment]
During my testing of my data filter changes, I also encountered this issue while trying to run applies on configurations that have changed.

I modified the get command in `resourceKeboolaSnowflakeWriterTablesUpdate` to cast to `*schema.Set` instead of `[]interface` to resolve the issue.

This cast is actually done on the create function, but was cast differently in the Update function. Seems odd since I would imagine the casts should be the same in both.

You can view the change in the following pull request: #50
