### ISSUE TITLE
Panic when running under Ubuntu

### ISSUE THREAD

**Issue by plmwong** [paybyphone/terraform-provider-keboola#43]
```
2018-07-12T11:15:18.283-0700 [DEBUG] plugin.terraform-provider-keboola: panic: runtime error: invalid memory address or nil pointer dereference
2018-07-12T11:15:18.283-0700 [DEBUG] plugin.terraform-provider-keboola: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xb567f4]
2018-07-12T11:15:18.283-0700 [DEBUG] plugin.terraform-provider-keboola:
2018-07-12T11:15:18.283-0700 [DEBUG] plugin.terraform-provider-keboola: goroutine 148 [running]:
2018-07-12T11:15:18.283-0700 [DEBUG] plugin.terraform-provider-keboola: github.com/plmwong/terraform-provider-keboola/plugin/providers/keboola.resourceKeboolaGoodDataWriterRead(0xc42022ca80, 0xd0af00, 0xc42010f8a0, 0xc42022ca80, 0x0)
2018-07-12T11:15:18.283-0700 [DEBUG] plugin.terraform-provider-keboola:         /mnt/c/go/src/github.com/plmwong/terraform-provider-keboola/plugin/providers/keboola/resource_keboola_gooddata_writer.go:135 +0x194
2018-07-12T11:15:18.283-0700 [DEBUG] plugin.terraform-provider-keboola: github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc42021e230, 0xc4201ae5a0, 0xd0af00, 0xc42010f8a0, 0xc42027f208, 0x4bf401, 0xbe3c20)
2018-07-12T11:15:18.283-0700 [DEBUG] plugin.terraform-provider-keboola:         /mnt/c/go/src/github.com/hashicorp/terraform/helper/schema/resource.go:355 +0x167
2018-07-12T11:15:18.283-0700 [DEBUG] plugin.terraform-provider-keboola: github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc42021efc0, 0xc4201ae550, 0xc4201ae5a0, 0x3, 0xc4201ccfc0, 0x1a)
2018-07-12T11:15:18.283-0700 [DEBUG] plugin.terraform-provider-keboola:         /mnt/c/go/src/github.com/hashicorp/terraform/helper/schema/provider.go:308 +0x9a
2018-07-12T11:15:18.283-0700 [DEBUG] plugin.terraform-provider-keboola: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc420478f80, 0xc42010faa0, 0xc42010fb70, 0x0, 0x0)
2018-07-12T11:15:18.283-0700 [DEBUG] plugin.terraform-provider-keboola:         /mnt/c/go/src/github.com/hashicorp/terraform/plugin/resource_provider.go:549 +0x4e
2018-07-12T11:15:18.283-0700 [DEBUG] plugin.terraform-provider-keboola: reflect.Value.call(0xc4201a3020, 0xc4203fe2e0, 0x13, 0xd69691, 0x4, 0xc42037af18, 0x3, 0x3, 0xc4201c62c0, 0xc420125b80, ...)
2018-07-12T11:15:18.283-0700 [DEBUG] plugin.terraform-provider-keboola:         /usr/lib/go-1.10/src/reflect/value.go:447 +0x969
2018-07-12T11:15:18.283-0700 [DEBUG] plugin.terraform-provider-keboola: reflect.Value.Call(0xc4201a3020, 0xc4203fe2e0, 0x13, 0xc4205aff18, 0x3, 0x3, 0xc420125cc0, 0xc420125ce0, 0xc420125d00)
2018-07-12T11:15:18.283-0700 [DEBUG] plugin.terraform-provider-keboola:         /usr/lib/go-1.10/src/reflect/value.go:308 +0xa4
2018-07-12T11:15:18.283-0700 [DEBUG] plugin.terraform-provider-keboola: net/rpc.(*service).call(0xc4201c6f00, 0xc420472410, 0xc42048a7e0, 0xc42048a7f0, 0xc4201ca680, 0xc4203dec00, 0xbe3be0, 0xc42010faa0, 0x16, 0xbe3c20, ...)
2018-07-12T11:15:18.283-0700 [DEBUG] plugin.terraform-provider-keboola:         /usr/lib/go-1.10/src/net/rpc/server.go:384 +0x14e
2018-07-12T11:15:18.283-0700 [DEBUG] plugin.terraform-provider-keboola: created by net/rpc.(*Server).ServeCodec
2018-07-12T11:15:18.283-0700 [DEBUG] plugin.terraform-provider-keboola:         /usr/lib/go-1.10/src/net/rpc/server.go:480 +0x43a
2018-07-12T11:15:18.293-0700 [DEBUG] plugin.terraform-provider-keboola: panic: runtime error: invalid memory address or nil pointer dereference
2018-07-12T11:15:18.293-0700 [DEBUG] plugin.terraform-provider-keboola: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xb791f1]
2018-07-12T11:15:18.293-0700 [DEBUG] plugin.terraform-provider-keboola:
2018-07-12T11:15:18.293-0700 [DEBUG] plugin.terraform-provider-keboola: goroutine 164 [running]:
2018-07-12T11:15:18.293-0700 [DEBUG] plugin.terraform-provider-keboola: github.com/plmwong/terraform-provider-keboola/plugin/providers/keboola.resourceKeboolaTransformBucketRead(0xc42021f490, 0xd0af00, 0xc42010f8a0, 0xc42021f490, 0x0)
2018-07-12T11:15:18.293-0700 [DEBUG] plugin.terraform-provider-keboola:         /mnt/c/go/src/github.com/plmwong/terraform-provider-keboola/plugin/providers/keboola/resource_keboola_transformation_bucket.go:54 +0x1a1
2018-07-12T11:15:18.293-0700 [DEBUG] plugin.terraform-provider-keboola: github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc42021e1c0, 0xc420472780, 0xd0af00, 0xc42010f8a0, 0xc42027f2e8, 0x4bf401, 0xbe3c20)
2018-07-12T11:15:18.293-0700 [DEBUG] plugin.terraform-provider-keboola:         /mnt/c/go/src/github.com/hashicorp/terraform/helper/schema/resource.go:355 +0x167
2018-07-12T11:15:18.293-0700 [DEBUG] plugin.terraform-provider-keboola: github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc42021efc0, 0xc420472730, 0xc420472780, 0x3, 0xc42048ec00, 0x1a)
2018-07-12T11:15:18.293-0700 [DEBUG] plugin.terraform-provider-keboola:         /mnt/c/go/src/github.com/hashicorp/terraform/helper/schema/provider.go:308 +0x9a
2018-07-12T11:15:18.293-0700 [DEBUG] plugin.terraform-provider-keboola: github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc420478f80, 0xc4203162e0, 0xc4203163b0, 0x0, 0x0)
2018-07-12T11:15:18.294-0700 [DEBUG] plugin.terraform-provider-keboola:         /mnt/c/go/src/github.com/hashicorp/terraform/plugin/resource_provider.go:549 +0x4e
2018-07-12T11:15:18.294-0700 [DEBUG] plugin.terraform-provider-keboola: reflect.Value.call(0xc4201a3020, 0xc4203fe2e0, 0x13, 0xd69691, 0x4, 0xc42037cf18, 0x3, 0x3, 0xc4201c75c0, 0x0, ...)
2018-07-12T11:15:18.294-0700 [DEBUG] plugin.terraform-provider-keboola:         /usr/lib/go-1.10/src/reflect/value.go:447 +0x969
2018-07-12T11:15:18.294-0700 [DEBUG] plugin.terraform-provider-keboola: reflect.Value.Call(0xc4201a3020, 0xc4203fe2e0, 0x13, 0xc42005b718, 0x3, 0x3, 0x0, 0x0, 0x0)
2018-07-12T11:15:18.294-0700 [DEBUG] plugin.terraform-provider-keboola:         /usr/lib/go-1.10/src/reflect/value.go:308 +0xa4
2018-07-12T11:15:18.294-0700 [DEBUG] plugin.terraform-provider-keboola: net/rpc.(*service).call(0xc4201c6f00, 0xc420472410, 0xc42048a7e0, 0xc42048a7f0, 0xc4201ca680, 0xc4203ded80, 0xbe3be0, 0xc4203162e0, 0x16, 0xbe3c20, ...)
2018-07-12T11:15:18.294-0700 [DEBUG] plugin.terraform-provider-keboola:         /usr/lib/go-1.10/src/net/rpc/server.go:384 +0x14e
2018-07-12T11:15:18.294-0700 [DEBUG] plugin.terraform-provider-keboola: created by net/rpc.(*Server).ServeCodec
2018-07-12T11:15:18.294-0700 [DEBUG] plugin.terraform-provider-keboola:         /usr/lib/go-1.10/src/net/rpc/server.go:480 +0x43a
2018-07-12T11:15:18.296-0700 [DEBUG] plugin: plugin process exited: path=/home/pwong/windows/source/repos/data/keboola-standard/terraform-provider-keboola
```

**Comment by plmwong** [comment]
Looks like `resourceKeboolaTransformBucketRead` and `resourceKeboolaGoodDataWriterRead` (and possibly others) are possibly `nil` pointer dereferencing. Not sure why this would be Linux specific though, as this behaviour does not appear in the Windows binaries that we use under Git Bash.

**Comment by plmwong** [comment]
The `panic` was a bit of a red herring, and it turned out to be an `interface` type mismatch which was easily fixed.
